In [1]:
from numpy import loadtxt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

2024-03-01 07:33:09.994376: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2024-03-01 07:33:12.839400: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-03-01 07:33:12.839499: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-03-01 07:33:13.247265: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-03-01 07:33:14.143648: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2024-03-01 07:33:14.145315: I tensorflow/core/platform/cpu_feature_guard.cc:1

In [4]:
# !pip install tensorflow

In [2]:
dataset = loadtxt("https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv", delimiter=',')

In [3]:
dataset

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [4]:
X= dataset[:,0:8]

In [5]:
X

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [6]:
y= dataset[:,8]

In [7]:
y

array([1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1.,
       1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1.,
       1., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0.,
       0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 0., 0., 0., 0.

In [8]:
Dense?

Init signature:
Dense(
    units,
    activation=None,
    use_bias=True,
    kernel_initializer='glorot_uniform',
    bias_initializer='zeros',
    kernel_regularizer=None,
    bias_regularizer=None,
    activity_regularizer=None,
    kernel_constraint=None,
    bias_constraint=None,
    **kwargs,
)
Docstring:     
Just your regular densely-connected NN layer.

`Dense` implements the operation:
`output = activation(dot(input, kernel) + bias)`
where `activation` is the element-wise activation function
passed as the `activation` argument, `kernel` is a weights matrix
created by the layer, and `bias` is a bias vector created by the layer
(only applicable if `use_bias` is `True`). These are all attributes of
`Dense`.

Note: If the input to the layer has a rank greater than 2, then `Dense`
computes the dot product between the `inputs` and the `kernel` along the
last axis of the `inputs` and axis 0 of the `kernel` (using `tf.tensordot`).
For example, if input has dimensions `(batch_size, d0

In [9]:
model = Sequential()
layer_1 = Dense(units=12, input_shape=(8,), activation="relu")
layer_2 = Dense(units=8, activation="relu")
layer_3 = Dense(units=1, activation="sigmoid")

In [10]:
a1=layer_1(X)

In [12]:
a2 = layer_2(a1)

In [13]:
a3 = layer_3(a2)

In [15]:
a1

<tf.Tensor: shape=(768, 12), dtype=float32, numpy=
array([[ 0.      ,  0.      ,  0.      , ..., 78.66187 ,  0.      ,
         0.      ],
       [ 0.      ,  0.      ,  0.      , ..., 48.227585,  0.      ,
         0.      ],
       [ 0.      ,  0.      ,  0.      , ..., 89.38772 ,  0.      ,
         0.      ],
       ...,
       [15.090893,  0.      , 21.058651, ..., 76.215775,  0.      ,
        19.915958],
       [ 0.      ,  0.      ,  0.      , ..., 61.55563 ,  0.      ,
         0.      ],
       [ 0.      ,  0.      ,  0.      , ..., 53.30157 ,  0.      ,
         0.      ]], dtype=float32)>

In [14]:
a2

<tf.Tensor: shape=(768, 8), dtype=float32, numpy=
array([[38.02662   , 15.121256  ,  6.6433754 , ...,  0.        ,
         0.        , 26.195967  ],
       [18.424423  ,  6.5994563 ,  0.13736773, ...,  0.        ,
         0.        , 13.876021  ],
       [51.17156   , 26.92768   , 17.213158  , ...,  0.        ,
         0.        , 36.138573  ],
       ...,
       [20.370281  ,  0.        , 25.551847  , ...,  0.        ,
         0.        ,  0.        ],
       [30.73043   ,  8.395538  , 11.115546  , ...,  0.        ,
         0.        , 11.157114  ],
       [20.894773  , 10.226177  ,  0.        , ...,  0.        ,
         0.        , 21.093313  ]], dtype=float32)>

In [16]:
a3

<tf.Tensor: shape=(768, 1), dtype=float32, numpy=
array([[2.20847940e-09],
       [5.24231745e-03],
       [1.45012487e-17],
       [7.57135494e-05],
       [5.50463231e-10],
       [1.25827466e-06],
       [4.12142370e-03],
       [1.74399019e-14],
       [5.70002089e-32],
       [1.64279133e-01],
       [5.46103111e-04],
       [2.63607783e-14],
       [3.10281503e-05],
       [0.00000000e+00],
       [1.79701694e-08],
       [2.27702215e-11],
       [6.57930030e-11],
       [2.76830324e-05],
       [5.79184189e-07],
       [5.59880864e-05],
       [3.38661564e-12],
       [9.69031870e-01],
       [1.30874627e-15],
       [6.61123636e-08],
       [4.93344078e-06],
       [7.49692435e-06],
       [2.85593571e-09],
       [5.18672664e-07],
       [1.53824425e-04],
       [9.71375848e-04],
       [2.32119367e-01],
       [1.64040201e-12],
       [3.28595215e-03],
       [2.11611986e-01],
       [7.97597295e-06],
       [6.20516172e-09],
       [1.94522531e-09],
       [4.78897011e-03],


In [17]:
X.shape

(768, 8)

In [18]:
model.add(layer_1)
model.add(layer_2)
model.add(layer_3)

In [19]:
model.compile(loss="binary_crossentropy", optimizer = "adam",metrics = ["accuracy"])

In [22]:
model.fit(X,y, epochs=150, batch_size=100)

Epoch 1/150
8/8 [==============================] - 1s 2ms/step - loss: 6.7356 - accuracy: 0.5456
Epoch 2/150
8/8 [==============================] - 0s 1ms/step - loss: 5.0125 - accuracy: 0.4154
Epoch 3/150
8/8 [==============================] - 0s 1ms/step - loss: 4.4269 - accuracy: 0.3841
Epoch 4/150
8/8 [==============================] - 0s 1ms/step - loss: 3.4782 - accuracy: 0.4766
Epoch 5/150
8/8 [==============================] - 0s 1ms/step - loss: 2.9106 - accuracy: 0.5195
Epoch 6/150
8/8 [==============================] - 0s 1ms/step - loss: 2.4852 - accuracy: 0.4922
Epoch 7/150
8/8 [==============================] - 0s 2ms/step - loss: 2.2700 - accuracy: 0.4922
Epoch 8/150
8/8 [==============================] - 0s 1ms/step - loss: 2.1004 - accuracy: 0.4896
Epoch 9/150
8/8 [==============================] - 0s 1ms/step - loss: 1.8994 - accuracy: 0.4961
Epoch 10/150
8/8 [==============================] - 0s 1ms/step - loss: 1.6988 - accuracy: 0.5013
Epoch 11/150
8/8 [===========

In [23]:
_, accuracy = model.evaluate(X,y)

24/24 [==============================] - 0s 896us/step - loss: 0.5392 - accuracy: 0.7161


In [25]:
accuracy * 100

71.61458134651184