In [1]:
from numpy import loadtxt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

2024-03-03 09:41:47.364267: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2024-03-03 09:41:49.854879: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-03-03 09:41:49.854966: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-03-03 09:41:50.217426: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-03-03 09:41:50.983984: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2024-03-03 09:41:50.984834: I tensorflow/core/platform/cpu_feature_guard.cc:1

In [2]:
# !pip install tensorflow

In [3]:
dataset = loadtxt("https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv", delimiter=',')

In [4]:
dataset

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [5]:
X= dataset[:,0:8]

In [6]:
X

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [23]:
X.shape

(768, 8)

In [7]:
y= dataset[:,8]

In [8]:
y

array([1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1.,
       1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1.,
       1., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0.,
       0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 0., 0., 0., 0.

In [9]:
Dense?

Init signature:
Dense(
    units,
    activation=None,
    use_bias=True,
    kernel_initializer='glorot_uniform',
    bias_initializer='zeros',
    kernel_regularizer=None,
    bias_regularizer=None,
    activity_regularizer=None,
    kernel_constraint=None,
    bias_constraint=None,
    **kwargs,
)
Docstring:     
Just your regular densely-connected NN layer.

`Dense` implements the operation:
`output = activation(dot(input, kernel) + bias)`
where `activation` is the element-wise activation function
passed as the `activation` argument, `kernel` is a weights matrix
created by the layer, and `bias` is a bias vector created by the layer
(only applicable if `use_bias` is `True`). These are all attributes of
`Dense`.

Note: If the input to the layer has a rank greater than 2, then `Dense`
computes the dot product between the `inputs` and the `kernel` along the
last axis of the `inputs` and axis 0 of the `kernel` (using `tf.tensordot`).
For example, if input has dimensions `(batch_size, d0

In [10]:
model = Sequential()
layer_1 = Dense(units=12, input_shape=(8,), activation="relu")
layer_2 = Dense(units=8, activation="relu")
layer_3 = Dense(units=1, activation="sigmoid")

In [11]:
a1=layer_1(X)

In [12]:
a2 = layer_2(a1)

In [13]:
a3 = layer_3(a2)

In [14]:
a1  #12 neural networks, thus 12 activation values for 768 input vectors

<tf.Tensor: shape=(768, 12), dtype=float32, numpy=
array([[  0.      , 109.93961 ,  57.91752 , ...,  14.385197,   0.      ,
         72.143524],
       [  0.      ,  72.63017 ,  44.765278, ...,   0.      ,   0.      ,
         46.772392],
       [  0.      , 126.06733 ,  33.6356  , ...,  28.231182,   6.866677,
         77.814415],
       ...,
       [  0.      ,  75.293465,  45.340965, ...,  24.712992,  43.632435,
         65.009254],
       [  0.      ,  96.537575,  44.936428, ...,  26.971537,   7.61604 ,
         68.39608 ],
       [  0.      ,  78.466774,  42.827263, ...,   0.      ,   0.      ,
         46.703716]], dtype=float32)>

In [17]:
X.shape

(768, 8)

In [21]:
a1.numpy()

array([[  0.      , 109.93961 ,  57.91752 , ...,  14.385197,   0.      ,
         72.143524],
       [  0.      ,  72.63017 ,  44.765278, ...,   0.      ,   0.      ,
         46.772392],
       [  0.      , 126.06733 ,  33.6356  , ...,  28.231182,   6.866677,
         77.814415],
       ...,
       [  0.      ,  75.293465,  45.340965, ...,  24.712992,  43.632435,
         65.009254],
       [  0.      ,  96.537575,  44.936428, ...,  26.971537,   7.61604 ,
         68.39608 ],
       [  0.      ,  78.466774,  42.827263, ...,   0.      ,   0.      ,
         46.703716]], dtype=float32)

In [22]:
a1.numpy()[0]   # Each row-vector has 12 entries indicating 12 activation values

array([  0.      , 109.93961 ,  57.91752 ,  36.786316,   0.      ,
        71.90008 ,   0.      ,  35.9738  ,  12.365368,  14.385197,
         0.      ,  72.143524], dtype=float32)

In [19]:
a2

<tf.Tensor: shape=(768, 8), dtype=float32, numpy=
array([[ 0.      ,  0.      , 32.64112 , ..., 55.412437, 69.36698 ,
         0.      ],
       [ 0.      ,  0.      , 36.07628 , ..., 39.20076 , 31.862494,
         0.      ],
       [ 0.      ,  0.      , 16.45094 , ..., 60.415226, 84.08001 ,
         0.      ],
       ...,
       [ 0.      ,  0.      ,  0.      , ..., 28.705746, 76.02812 ,
         0.      ],
       [ 0.      ,  0.      , 27.229465, ..., 41.169243, 59.04902 ,
         0.      ],
       [ 0.      ,  0.      , 39.766903, ..., 44.75812 , 31.104065,
         0.      ]], dtype=float32)>

In [20]:
a2.numpy()

array([[ 0.      ,  0.      , 32.64112 , ..., 55.412437, 69.36698 ,
         0.      ],
       [ 0.      ,  0.      , 36.07628 , ..., 39.20076 , 31.862494,
         0.      ],
       [ 0.      ,  0.      , 16.45094 , ..., 60.415226, 84.08001 ,
         0.      ],
       ...,
       [ 0.      ,  0.      ,  0.      , ..., 28.705746, 76.02812 ,
         0.      ],
       [ 0.      ,  0.      , 27.229465, ..., 41.169243, 59.04902 ,
         0.      ],
       [ 0.      ,  0.      , 39.766903, ..., 44.75812 , 31.104065,
         0.      ]], dtype=float32)

In [25]:
a2.numpy()[0]# Each row-vector has 8 entries indicating 12 activation values

array([ 0.      ,  0.      , 32.64112 ,  0.      , 22.837307, 55.412437,
       69.36698 ,  0.      ], dtype=float32)

In [26]:
a3 # 1 activation value for 768 input vectors.

<tf.Tensor: shape=(768, 1), dtype=float32, numpy=
array([[1.00000000e+00],
       [3.48752365e-05],
       [1.00000000e+00],
       [1.00000000e+00],
       [1.00000000e+00],
       [9.05677862e-03],
       [1.00000000e+00],
       [1.00000000e+00],
       [1.00000000e+00],
       [9.99907494e-01],
       [2.33048975e-12],
       [9.99992967e-01],
       [9.99994993e-01],
       [1.00000000e+00],
       [1.00000000e+00],
       [1.00000000e+00],
       [1.00000000e+00],
       [4.50004591e-05],
       [1.00000000e+00],
       [1.00000000e+00],
       [1.00000000e+00],
       [4.36652840e-07],
       [9.99999285e-01],
       [3.92727926e-03],
       [1.00000000e+00],
       [1.00000000e+00],
       [9.89581704e-01],
       [1.00000000e+00],
       [1.00000000e+00],
       [1.10741407e-08],
       [1.43795788e-01],
       [1.00000000e+00],
       [1.00000000e+00],
       [3.18370261e-11],
       [9.49332416e-01],
       [1.00000000e+00],
       [8.25562775e-01],
       [2.87208427e-03],


In [17]:
X.shape

(768, 8)

In [18]:
model.add(layer_1)
model.add(layer_2)
model.add(layer_3)

In [19]:
model.compile(loss="binary_crossentropy", optimizer = "adam",metrics = ["accuracy"])

In [22]:
model.fit(X,y, epochs=150, batch_size=100)

Epoch 1/150
8/8 [==============================] - 1s 2ms/step - loss: 6.7356 - accuracy: 0.5456
Epoch 2/150
8/8 [==============================] - 0s 1ms/step - loss: 5.0125 - accuracy: 0.4154
Epoch 3/150
8/8 [==============================] - 0s 1ms/step - loss: 4.4269 - accuracy: 0.3841
Epoch 4/150
8/8 [==============================] - 0s 1ms/step - loss: 3.4782 - accuracy: 0.4766
Epoch 5/150
8/8 [==============================] - 0s 1ms/step - loss: 2.9106 - accuracy: 0.5195
Epoch 6/150
8/8 [==============================] - 0s 1ms/step - loss: 2.4852 - accuracy: 0.4922
Epoch 7/150
8/8 [==============================] - 0s 2ms/step - loss: 2.2700 - accuracy: 0.4922
Epoch 8/150
8/8 [==============================] - 0s 1ms/step - loss: 2.1004 - accuracy: 0.4896
Epoch 9/150
8/8 [==============================] - 0s 1ms/step - loss: 1.8994 - accuracy: 0.4961
Epoch 10/150
8/8 [==============================] - 0s 1ms/step - loss: 1.6988 - accuracy: 0.5013
Epoch 11/150
8/8 [===========

In [23]:
_, accuracy = model.evaluate(X,y)

24/24 [==============================] - 0s 896us/step - loss: 0.5392 - accuracy: 0.7161


In [25]:
accuracy * 100

71.61458134651184